name: CI devops

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build + Test + Sonar
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=Jacq-VENGADESAN_tp-devops-docker -Dsonar.organization=jacq-vengadesan -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./backend/simple-api/pom.xml

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend/simple-api
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest